#pragma once

// Generated by tools/update_credits.js, do not edit by hand.
// Add, rename or hide people through supporters_overrides.json instead.

#include <array>
#include <cstdint>

namespace Supporters {
    enum class Platform : uint8_t {
        GITHUB,
        PATREON,
        OTHER
    };

    struct Supporter {
        const char* name;
        Platform platform;
    };

    inline constexpr const char* LastUpdated = "2026-08-07";

    inline constexpr std::array<Supporter, 10> List = {{
        { "Dash Schlotterbeck", Platform::GITHUB },
        { "beepsandblips", Platform::GITHUB },
        { "Carlos4321", Platform::GITHUB },
        { "darkmoldavite", Platform::GITHUB },
        { "giodude12", Platform::GITHUB },
        { "Hannah_K.", Platform::GITHUB },
        { "masterofmemes", Platform::GITHUB },
        { "Tim Dawson", Platform::GITHUB },
        { "Canible", Platform::GITHUB },
        { "available-nickname1", Platform::GITHUB },
    }};
}
